FROM ubuntu:16.04

# Essentials
RUN apt update
RUN apt install -y git python-pip python3-pip curl build-essential feh compton wget

# i3
RUN /usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2018.01.30_all.deb keyring.deb SHA256:baa43dbbd7232ea2b5444cae238d53bebb9d34601cc000e82f11111b1889078a
RUN dpkg -i ./keyring.deb
RUN echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list

RUN apt update
RUN apt install -y i3

# i3 gaps -> xcb
RUN apt install -y libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev \
                libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev \
                libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev \
                libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf

# i3 gaps -> xcb-util-xrm
RUN wget https://github.com/Airblader/xcb-util-xrm/releases/download/v1.3/xcb-util-xrm-1.3.tar.gz
RUN tar -zxf xcb-util-xrm-1.3.tar.gz
WORKDIR ./xcb-util-xrm-1.3
RUN ./configure
RUN make
RUN make install
WORKDIR ../

# i3-gaps
RUN git clone https://www.github.com/Airblader/i3 i3-gaps
WORKDIR ./i3-gaps
RUN autoreconf --force --install
RUN rm -rf build/
RUN mkdir -p build
WORKDIR ./build
RUN ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
RUN make
RUN make install
WORKDIR ../../

# Yabar
RUN apt install -y libcairo2-dev libpango1.0-dev libconfig-dev libxcb-randr0-dev \
                libxcb-ewmh-dev libxcb-icccm4-dev libgdk-pixbuf2.0-dev libasound2-dev \
                libiw-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-xkb-dev
RUN git clone https://github.com/geommer/yabar.git
WORKDIR ./yabar
RUN make yabar
RUN sed -i "/\b\(MANPREFIX\)\b/d" Makefile
RUN make install
WORKDIR ../

# Rofi -> apt dependencies
RUN apt install -y autoconf automake flex xcb libpango1.0-dev \
                libpangocairo-1.0-0 librsvg2-dev libstartup-notification0-dev \
                libxkbcommon-dev libxkbcommon-x11-dev
# Rofi -> Bison parser
RUN wget http://mirror.ibcp.fr/pub/gnu/bison/bison-1.25.tar.gz
RUN tar -xvf bison-1.25.tar.gz
WORKDIR ./bison-1.25
RUN ./configure
RUN make
RUN make install
WORKDIR ../

# Rofi -> Check >= 0.11
RUN wget https://github.com/libcheck/check/releases/download/0.12.0/check-0.12.0.tar.gz
RUN tar -zxf check-0.12.0.tar.gz
WORKDIR ./check-0.12.0
RUN ./configure
RUN make
RUN make install
WORKDIR ../

# Rofi
RUN wget https://github.com/DaveDavenport/rofi/releases/download/1.5.1/rofi-1.5.1.tar.gz
RUN tar -xvf rofi-1.5.1.tar.gz
WORKDIR ./rofi-1.5.1
RUN ./configure
RUN make
RUN make install
WORKDIR ../

# Yabar script utils
RUN pip install i3ipc
